# Default values for helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  # -- Hostname to be used for default hostpaths in ingress, prefixed with the charts name
  nameOverride: ""
  # -- Hostname prefix to be used for default hostpaths in ingress
  fullnameOverride: ""

  # -- Domain suffix to be used for default hostpaths in ingress
  ingressSuffix: .acapy

  persistence:
    # -- Name of existing secret to use for PostgreSQL passwords
    existingSecret: false

  # -- The used ledger. Will be used for default values. Any of: idu, bcovrin-test
  ledger: bcovrin-test

image:
  repository: bcgovimages/aries-cloudagent
  pullPolicy: IfNotPresent
  # --  Overrides the image tag whose default is the chart appVersion.
  tag: py36-1.16-1_0.7.4

# If using diode cli, expose the inbound port
endPointUrl: ""

inbound: 
  module:
  host: 
  port:

serviceAccount:
  # -- Specifies whether a service account should be created
  create: false
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name: 

vault:
  # Enable to obtain admin_key (api key), tenant jwtSecret, seed 
  # and wallet_key as well as postgres username and password from vault
  enabled: false
  postgresql_admin_username: 
  postgresql_admin_password: 
  postgresUserGroup: 
  postgres_ip: 
  # Used to authenticate service accounts with vault
  kubernetes_authentication_role_names:
    database: 
    acapy: 
    sharedServices: 
  vaultAddress:
  vault_server_url:
  vaultCACertPath: 

admin:
  # Specify the host and port on which to run the
  # administrative server. If not provided, no admin
  # server is made available.
  # Readiness and liveness checks will fail if not enabled
  enabled: 
  host: 0.0.0.0
  # Enable or disable admin url api key
  apiKey:
    enabled:
    # -- Please change: key used to protect acapy's admin endpoint
    # Either set this OR set adminInsecureMode
    adminURLApiKey: ""
    adminInsecureMode: 

db:
  username:
  password: ""
  host:
  port:
  database:

# -- Please change: the agent seed, 32 characters e.g. a UUID without the dashes. If the ledger is bcovrin-test the seed will be registered automatically. In all other cases this needs to happen manually beforehand.
# Do not set in multitenant mode
agentSeed: ""
# -- Please change: Wallet encryption key, be aware that if this value is changed later aca-py needs to be restarted with the '--wallet-rekey' param which is not mapped
walletKey: ""

# Send webhooks containing internal state changes to the
# specified URL. Optional API key to be passed in the
# request body can be appended using a hash separator
# [#] <url#api_key>
webhookUrl: ""

# After startup, generate and print a new out-of-band
# connection invitation URL. Default: false.
invite:

# Specify the label of the generated invitation
inviteLabel: ""

# Generate tracing events.  Default: false
trace:

# Target for trace events ("log", "message", or http endpoint)
traceTarget: ""

# Tag to be included when logging events
traceTag: ""

# Label (agent name) used logging events
traceLabel: ""

# Specifies the image url for this agent.
imageUrl: ""

# Specifies a new master key value to which to rotate
# and to open the wallet next time
walletRekey: ""

# If this parameter is set and an agent already has a
# public DID, and the '--seed' parameter specifies a new
# DID, the agent will use the new DID in place of the
# existing DID. Default: false.
replacePublic:

# If an existing wallet exists with the same name,
# remove and recreate it during provisioning.  Default: false
recreateWallet:

labelOverride: ""

readOnlyMode: false

staticArgs:
  autoAcceptInvites: false
  autoAcceptRequests: false
  autoRespondMessages: false
  autoRespondCredentialProposal: false
  autoRespondCredentialOffer: false
  autoRespondCredentialRequest: false
  autoRespondPresentationProposal: true
  autoRespondPresentationRequest: false
  autoStoreCredential: true
  autoVerifyPresentation: false
  autoPingConnection: true
  autoProvision: false
  autoDiscloseFeatures: true
  notifyRevocation: true
  monitorRevocationNotification: true
  monitorPing: true
  emitNewDidcommPrefix: true
  emitNewDidcommMimeType: true
  enableUndeliveredQueue: true
  exchUseUnencryptedTags: true
  preserveExchangeRecords: false
  publicInvites: true
  logLevel: debug
  # -- indy or askar
  walletType: askar
  
  # If this parameter is set, allows to use a custom seed to create a local DID
  walletAllowInsecureSeed: true

  # Multi Tenancy
  # This enables multi-tenancy in ACA-Py
  multitenant: false

  # This enables the admin API for multi-tenancy. More information below
  multitenantAdmin: true

  # This sets the secret used for JWT creation/verification for sub wallets
  jwtSecret: cOWwvAe7XqR3Q9BrvW7OnCFf0ZolPH57X3vROQkH

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  runAsUser: 1001

service:
  type: ClusterIP
  clusterIP: 
  adminPort: 8031
  httpPort: 8030

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"

  # Uncomment this to define your own hosts and override global.ingressSuffix
  # hosts:
  #     host:
  #     paths: ['/']
  tls: []
  #  - secretName: my-acapy-tls
  #    hosts:
  #      - my-acapy.local
  className: ""

openshift:
  route:
    enabled: false
    path: "/"
    targetPort: http
    timeout: 30s
    tls:
      enabled: true
      insecureEdgeTerminationPolicy: None
      termination: edge
    wildcardPolicy: None

tails:
  # -- Set to true to enable revocation (external tails server required)
  enabled: false

  # -- Override the otherwise ledger-specifically generated base URL of the external tails server
  baseUrlOverride: ""

  # -- Override the otherwise ledger-specifically generated upload URL of the external tails server
  uploadUrlOverride: ""

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
