{{- if (include "acapy.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "acapy.fullname" . }}
  labels:
    {{- include "acapy.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
stringData:
  {{- if .Values.acapy.admin.apiKey -}}
  ACAPY_ADMIN_URL_API_KEY: {{ required "acapy.admin.adminURLApiKey is required" .Values.acapy.admin.apiKey.adminURLApiKey | quote }}
  {{- end -}}
  ACAPY_AGENT_SEED: {{ required "acapy.agentSeed is required" .Values.acapy.agentSeed | quote }}
  ACAPY_WALLET_KEY: {{ required "acapy.walletKey is required" .Values.acapy.walletKey | quote }}
type: Opaque
{{- end -}}