{{- if (include "acapy.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "acapy.fullname" . }}-acapy
  labels:
    {{- include "acapy.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
stringData:
  {{- if .Values.admin.apiKey.enabled }}
  ACAPY_ADMIN_URL_API_KEY: {{ .Values.admin.apiKey.adminURLApiKey | quote }}
  {{- end }}
  ACAPY_AGENT_SEED: {{ .Values.agentSeed | quote }}
  ACAPY_WALLET_KEY: {{ .Values.walletKey | quote }}
type: Opaque
{{- end -}}