{{- if (include "acapy.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "acapy.fullname" . }}-acapy
  labels:
    {{- include "acapy.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
stringData:
  {{- if .Values.admin.apiKey.enabled }}
  ACAPY_ADMIN_API_KEY: {{ .Values.admin.apiKey.adminURLApiKey | quote }}
  {{- else }}
  ACAPY_ADMIN_INSECURE_MODE: {{ .Values.admin.apiKey.adminInsecureMode | quote }}
  {{- end }}
  {{- if .Values.agentSeed }}
  ACAPY_WALLET_SEED: {{ .Values.agentSeed | quote }}
  {{- end }}
  ACAPY_WALLET_KEY: {{ .Values.walletKey | quote }}
  {{- if .Values.staticArgs.multitenant }}
  ACAPY_MULTITENANT_JWT_SECRET: {{ .Values.staticArgs.jwtSecret | quote }}
  {{- end }}
type: Opaque
{{- end -}}