apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "acapy.fullname" . }}
  labels:
    {{- include "acapy.labels" . | nindent 4 }}
data:
  acapy-static-args.yaml: |
    auto-accept-invites: {{ .Values.staticArgs.autoAcceptInvites }}
    auto-accept-requests: {{ .Values.staticArgs.autoAcceptRequests }}
    auto-respond-messages: {{ .Values.staticArgs.autoRespondMessages }}
    auto-respond-credential-proposal: {{ .Values.staticArgs.autoRespondCredentialProposal }}
    auto-respond-credential-offer: {{ .Values.staticArgs.autoRespondCredentialOffer }}
    auto-respond-credential-request: {{ .Values.staticArgs.autoRespondCredentialRequest }}
    auto-respond-presentation-proposal: {{ .Values.staticArgs.autoRespondPresentationProposal }}
    auto-respond-presentation-request: {{ .Values.staticArgs.autoRespondPresentationRequest }}
    auto-store-credential: {{ .Values.staticArgs.autoStoreCredential }}
    auto-verify-presentation: {{ .Values.staticArgs.autoVerifyPresentation }}
    auto-ping-connection: {{ .Values.staticArgs.autoPingConnection }}
    auto-provision: {{ .Values.staticArgs.autoProvision }}
    auto-disclose-features: {{ .Values.staticArgs.autoDiscloseFeatures }}
    notify-revocation: {{ .Values.staticArgs.notifyRevocation }}
    monitor-revocation-notification: {{ .Values.staticArgs.monitorRevocationNotification }}
    monitor-ping: {{ .Values.staticArgs.monitorPing }}
    emit-new-didcomm-prefix: {{ .Values.staticArgs.emitNewDidcommPrefix }}
    emit-new-didcomm-mime-type: {{ .Values.staticArgs.emitNewDidcommMimeType }}
    enable-undelivered-queue: {{ .Values.staticArgs.enableUndeliveredQueue }}
    exch-use-unencrypted-tags: {{ .Values.staticArgs.exchUseUnencryptedTags }}
    preserve-exchange-records: {{ .Values.staticArgs.preserveExchangeRecords }}
    public-invites: {{ .Values.staticArgs.publicInvites }}
    plugin: 'aries_cloudagent.messaging.jsonld'
    outbound-transport: http
    log-level: {{ .Values.staticArgs.logLevel }}
    wallet-type: {{ .Values.staticArgs.walletType }}
    wallet-allow-insecure-seed: {{ .Values.staticArgs.walletAllowInsecureSeed }}
    multitenant: {{ .Values.staticArgs.multitenant }}
    multitenant-admin: {{ .Values.staticArgs.multitenantAdmin }}
  genesis-transaction-list.yaml: |
    - id: bcovrinTest
      is_production: {{ include "acapy.writeLedger" (list . (dict "ledger" "bcovrin-test")) }}
      is_write: {{ include "acapy.writeLedger" (list . (dict "ledger" "bcovrin-test")) }}
      genesis_url: 'http://test.bcovrin.vonx.io/genesis'
    - id: IDUnionTest
      is_production: {{ include "acapy.writeLedger" (list . (dict "ledger" "idu")) }}
      is_write: {{ include "acapy.writeLedger" (list . (dict "ledger" "idu")) }}
      genesis_url: 'https://raw.githubusercontent.com/IDunion/IDunion_TestNet_Genesis/master/pool_transactions_genesis'
    - id: SovrinBuilderNet
      is_production: false
      is_write: false
      genesis_url: 'https://raw.githubusercontent.com/sovrin-foundation/sovrin/stable/sovrin/pool_transactions_builder_genesis'
    - id: SuomiTestNet
      is_production: false
      is_write: false
      genesis_url: 'https://minisuomiledger.northeurope.cloudapp.azure.com/genesis'
    - id: iGrantTestNet
      is_production: false
      is_write: false
      genesis_url: 'https://indy.igrant.io/genesis'