{{- if and (not .Values.global.persistence.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "acapy.fullname" . }}-db
  labels:
    app: {{ template "global.name" . }}
    chart: {{ template "global.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  postgresql-password: {{ .Values.db.password | quote }}
  postgresql-username: {{ .Values.db.username | quote }}
{{- end -}}