{{- if and (not .Values.global.persistence.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "global.postgresql.fullname" . }}
  labels:
    app: {{ template "global.name" . }}
    chart: {{ template "global.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  postgresql-password: {{ .Values.postgresql.postgresqlPassword | quote }}
  postgresql-username: {{ .Values.postgresql.postgresqlUsername | quote }}
{{- end -}}