{{- if .Values.vault.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: read-db-credentials
spec:
  provider: vault
  secretObjects:
    - data:
      - key: postgresql-username
        objectName: postgresql-username
      - key: postgresql-password
        objectName: postgresql-password
      secretName: vault-db-credentials
      type: Opaque
  parameters:
    roleName: 'database'
    vaultAddress: {{ .Values.vault.vaultAddress | quote }}
    vaultCACertPath: {{ .Values.vault.vaultCACertPath | quote }}
    objects: |
      - objectName: "postgresql-username"
        secretPath: "database/creds/admin"
        secretKey: "username"
      - objectName: "postgresql-password"
        secretPath: "database/creds/admin"
        secretKey: "password"
{{- end -}}