{{- if .Values.vault.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ template "acapy.fullname" . }}-vault-database-creds
  labels:
    app: {{ template "global.name" . }}
    chart: {{ template "global.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  provider: vault
  secretObjects:
    - data:
      - key: postgresql_username
        objectName: postgresql_username
      - key: postgresql_password
        objectName: postgresql_password
      secretName: {{ template "acapy.fullname" . }}-vault-database-creds
      type: Opaque
  parameters:
    roleName: {{ .Values.vault.kubernetes_authentication_role_names.database | quote }}
    vaultAddress: {{ .Values.vault.vaultAddress | quote }}
    vaultCACertPath: {{ .Values.vault.vaultCACertPath | quote }}
    objects: |
      - objectName: "postgresql_username"
        secretPath: "database/creds/{{ .Values.vault.postgresUserGroup }}"
        secretKey: "username"
      - objectName: "postgresql_password"
        secretPath: "database/creds/{{ .Values.vault.postgresUserGroup }}"
        secretKey: "password"
{{- end }}