{{- if .Values.vault.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ template "acapy.fullname" . }}-vault-secret-acapy
  labels:
    app: {{ template "global.name" . }}
    chart: {{ template "global.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  provider: vault
  secretObjects:
    - data:
      - key: acapy_seed
        objectName: acapy_seed
      - key: acapy_wallet_key
        objectName: acapy_wallet_key
      - key: acapy_multitenant_jwt_secret
        objectName: acapy_multitenant_jwt_secret
      secretName: {{ template "acapy.fullname" . }}-vault-secret-acapy
      type: Opaque
  parameters:
    roleName: {{ .Values.vault.kubernetes_authentication_role_names.acapy | quote }}
    vaultAddress: {{ .Values.vault.vaultAddress | quote }}
    vaultCACertPath: {{ .Values.vault.vaultCACertPath | quote }}
    objects: |
      - objectName: "acapy_seed"
        secretPath: "secret/acapy/data/{{ .Values.vault.postgresUserGroup }}"
        secretKey: "acapy_seed"
      - objectName: "acapy_wallet_key"
        secretPath: "secret/acapy/data/{{ .Values.vault.postgresUserGroup }}"
        secretKey: "acapy_wallet_key"
      - objectName: "acapy_multitenant_jwt_secret"
        secretPath: "secret/acapy/data/{{ .Values.vault.postgresUserGroup }}"
        secretKey: "acapy_multitenant_jwt_secret"
{{- end }}