{{- if .Values.vault.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ template "acapy.fullname" . }}-vault-secret-shared-services
  labels:
    app: {{ template "global.name" . }}
    chart: {{ template "global.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  provider: vault
  secretObjects:
    - data:
      - key: acapy_admin_api_key
        objectName: acapy_admin_api_key
      secretName: {{ template "acapy.fullname" . }}-vault-secret-shared-services
      type: Opaque
  parameters:
    roleName: {{ .Values.vault.kubernetes_authentication_role_names.sharedServices | quote }}
    vaultAddress: {{ .Values.vault.vaultAddress | quote }}
    vaultCACertPath: {{ .Values.vault.vaultCACertPath | quote }}
    objects: |
      - objectName: acapy_admin_api_key
        secretPath: secret/shared_services/data/shared_services_kv_secret
        secretKey: acapy_admin_api_key
{{- end }}